cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('product_list/', views.product_list, name='product_list'),
    path('about/', views.about_us, name='about_us'),
    path('contact/', views.contact_us, name='contact_us'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from cart.cart import Cart
from cart.forms import CartAddProductForm
from shop.models import Product
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    coupon_apply_form = CouponApplyForm
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'shop/csss/style.css' %}">
</head>
<body>
	<main class="page">
	 	<section class="shopping-cart dark">
	 		<div class="container">
		        <div class="block-heading">
		          <h2>Shopping Cart</h2>
		          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
		        </div>
		        <div class="content">
	 				<div class="row">
                        {% for item in cart %}
                            {% with product=item.product %}
                                <div class="col-md-12 col-lg-8">
                                    <div class="items">
                                        <div class="product">
                                            <div class="row">
                                                <div class="col-md-3">
                                                    <a href="{{ product.get_absolute_url }}">
                                                        {% thumbnail product.image 100x100 crop='smatr' as im %}
                                                        <img class="img-fluid mx-auto d-block image" src="{{ im.url }}">
                                                    </a>
                                                </div>
                                                <div class="col-md-8">
                                                    <div class="info">
                                                        <div class="row">
                                                            <div class="col-md-5 product-name">
                                                                <div class="product-name">
                                                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                                                    <div class="product-info">
                                                                        <div> <span class="value">{% if product.description %}{{ product.description|truncatechars:50|linebreaks }} {% else %} <light>product has no description</light>{% endif %}</span></div>
                                                                    </div>
                                                                </div>
                                                            <form action="{% url "cart:cart_remove" product.id %}"
                                                                method="post">
                                                                <input type="submit" value="Remove">
                                                                {% csrf_token %}
                                                            </form>
                                                            </div>
                                                            <div class="col-md-4 quantity">
                                                                    <label for="quantity">Quantity:</label>
                                                                    <div>
                                                                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                                            <div>
                                                                            {{ item.update_quantity_form.quantity }}
                                                                            {{ item.update_quantity_form.override }}
                                                                            </div>
                                                                            <input type="submit" value="Update">
                                                                            {% csrf_token %}
                                                                        </form>
                                                                    </div>
                                                            </div>
                                                            <div class="col-md-3 price">
                                                                <span>${{ product.price }}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endwith %}
                        {% endfor %}
			 			<div class="col-md-12 col-lg-4">
			 				<div class="summary">
			 					<h3>{% if cart.get_total_price == 0 %}Your cart is empty! :({% else %}Summary{% endif %}</h3>
			 					<div class="summary-item"><span class="text">Total</span><span class="price">${{ cart.get_total_price }}</span></div>
                                <a href="{% url 'orders:order_create' %}"><button type="button" class="btn btn-primary btn-lg btn-block">Checkout</button></a>
                                <a href="{% url 'shop:product_list' %}"><button type="button" class="btn btn-primary btn-lg btn-block">Continue shopping</button></a>
				 			</div>
			 			</div>
		 			</div>
		 		</div>
	 		</div>
		</section>
	</main>
</body>
{% endblock %}